name: Generate Descriptions

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install openai playwright
          playwright install --with-deps

      - name: Run script and show result
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "🔹 Начинаем генерацию..."
          python main.py
          echo "🔹 Выполнено!"
